// Reality rTokens on Arbitrum One (chainId 42161): ERC-20s issued by Reality (Bitget), 1:1 backed by
// shares held with a US broker-dealer. Doppler announced rToken-paired markets on 2026-09-14.
//
// Generated by `npx tsx scripts/discover-reality.ts` from Bitget's RWA API (POST /bgw-pro/market/v3/rwa/stockList,
// data_source "reality", Arbitrum contracts), every address then verified on-chain (symbol/name/decimals).
// Do not hand-edit: rerun the script. Empty until the first discovery run.
import type { Stock } from "./stocks-types"

export const STOCKS_42161: Stock[] = []
