// Reality rTokens on Arbitrum One (chainId 42161): ERC-20s issued by Reality (Bitget), 1:1 backed by
// shares held with a US broker-dealer. Doppler announced rToken-paired markets on 2026-09-14.
//
// Data lives in stocks-arbitrum.json as [ticker, name, address, logo, decimals, symbolOnChain] rows
// (1,700+ object literals blow up the TypeScript checker). Generated by `npx tsx scripts/discover-reality.ts`
// from Bitget's RWA API (POST /bgw-pro/market/v3/rwa/stockList, data_source "reality", chain "arbitrum"),
// every address verified on-chain (symbol/name/decimals via Arbitrum RPC). Do not hand-edit: rerun the script.
import type { Stock } from "./stocks-types"
import rows from "./stocks-arbitrum.json"

type Row = [ticker: string, name: string, address: string, logo: string, decimals: number, symbolOnChain: string]

export const STOCKS_42161: Stock[] = (rows as Row[]).map(([ticker, name, address, logo, decimals, symbolOnChain]) => ({
  ticker,
  name,
  address: address as `0x${string}`,
  logo,
  decimals,
  issuer: "reality",
  symbolOnChain,
}))
